import json

class mod_data:
    def __init__(self):
         a = 'false'

    def getData(self):
        false = False
        true = True
        params={"name":"嗯嗯嗯",
                "name_zh_tw":"",
                "name_en":"",
                "coverUrl":"https://oss.zhiyun-tech.com/zyplaytest/templates/47/2020-04-15-17:49:05.png",
                "videoUrl":"https://oss.zhiyun-tech.com/zyplaytest/5aa2363ed3f8bf6299ecbad04c989332.mp4",
                "videoTime":"100",
                "resUrl":"",
                "isPkg":"0",
                "sort":"1",
                "publish":"1",
                "typeId":"177",
                "config":"JSON字符串",
                "z_film_config":"JSON字符串",
                "videoCount":"2",
                "videoRatio":"9:16",
                "resSize":"3138356"}

        config={"global":
                    {"duration":100,
                     "timebase":100,
                     "rotate":{"enable":false,
                               "rotate":0},
                     "render":{"renderSize":"9:16"},
                     "effect":{"enable":false,
                               "vignette":"",
                               "sharpen":""},
                     "filter":{"enable":false,
                               "isLocalSource":false,
                               "name":"",
                               "strength":0,
                               "type":"filter"},
                     "music":{"startTime":0,
                              "timebase":50,
                              "volume":0,
                              "mute":false,
                              "name":"",
                              "isLocalSource":false},
                     "musics":[],
                     "stickers":[{"startTime":0,
                                  "angle":0,
                                  "center":"0,0",
                                  "type":"text",
                                  "scale":0,
                                  "text":{"isLocalSource":false,
                                          "fontSize":1,
                                          "fontName":"",
                                          "textColor":"",
                                          "text":"",
                                          "caption":{"name":"",
                                                     "isLocalSource":false,
                                                     "type":"style"},
                                          "type":"text"}},
                                 {"startTime":0,
                                  "endTime":0,
                                  "angle":0,
                                  "center":"0,0",
                                  "type":"image",
                                  "scale":0,
                                  "image":{"isLocalSource":false,
                                           "name":""}}]},
                "slices":[{"tabconfig":{"canClose":true},
                           "timebase":60,
                           "startTime":0,
                           "duration":10,
                           "mute":false,
                           "volume":0,
                           "rate":1,
                           "rotate":{"enable":false,
                                     "rotate":0},
                           "filter":{"isLocalSource":true,
                                     "enable":false,
                                     "name":"",
                                     "strength":0,
                                     "type":"filter",
                                     "enabled":false},
                           "effect":{"enable":false,
                                     "vignette":"",
                                     "sharpen":""},
                           "transition":{"isLocalSource":false,
                                         "name":"",
                                         "duration":"",
                                         "timebase":60,
                                         "type":"transition"}},
                          {"tabconfig":{"canClose":true},
                           "timebase":60,
                           "startTime":0,
                           "endTime":3,
                           "duration":10,
                           "mute":false,
                           "volume":0,
                           "rate":1,
                           "rotate":{"enable":false,
                                     "rotate":0},
                           "filter":{"isLocalSource":true,
                                     "enable":false,
                                     "name":"",
                                     "strength":0,
                                     "type":"filter",
                                     "enabled":false},
                           "effect":{"enable":false,
                                     "vignette":"",
                                     "sharpen":""},
                           "transition":{"isLocalSource":false,
                                         "name":"",
                                         "duration":"",
                                         "timebase":60,
                                         "type":"transition"}}]}


        z_film_config={"global":
                           {"duration":100,
                            "timebase":100,
                            "rotate":{"enable":false,
                                      "rotate":0},
                            "render":{"renderSize":"9:16"},
                            "effect":{"enable":false,
                                      "vignette":"",
                                      "sharpen":""},
                            "filter":{"enable":false,
                                      "isLocalSource":false,
                                      "name":"",
                                      "strength":0,
                                      "type":"filter"},
                            "music":{"startTime":0,
                                     "timebase":50,
                                     "volume":0,
                                     "mute":false,
                                     "name":"",
                                     "isLocalSource":false},
                            "musics":[],
                            "stickers":[{"startTime":0,
                                         "angle":0,
                                         "center":"0,0",
                                         "type":"text",
                                         "scale":0,
                                         "text":{"isLocalSource":false,
                                                 "fontSize":1,
                                                 "fontName":"",
                                                 "textColor":"",
                                                 "text":"",
                                                 "caption":{"name":"",
                                                            "isLocalSource":false,
                                                            "type":"style"},
                                                 "type":"text"}},
                                        {"startTime":0,
                                         "endTime":0,
                                         "angle":0,
                                         "center":"0,0",
                                         "type":"image",
                                         "scale":0,
                                         "image":{"isLocalSource":false,
                                                  "name":""}}]},
                       "slices":[{"tabconfig":{"canClose":true},
                                  "timebase":60,
                                  "startTime":0,
                                  "duration":10,
                                  "mute":false,
                                  "volume":0,
                                  "rate":1,
                                  "rotate":{"enable":false,
                                            "rotate":0},
                                  "filter":{"isLocalSource":true,
                                            "enable":false,
                                            "name":"",
                                            "strength":0,
                                            "type":"filter",
                                            "enabled":false},
                                  "effect":{"enable":false,
                                            "vignette":"",
                                            "sharpen":""},
                                  "transition":{"isLocalSource":false,
                                                "name":"",
                                                "duration":"",
                                                "timebase":60,
                                                "type":"transition"}},
                                 {"tabconfig":{"canClose":true},
                                  "timebase":60,
                                  "startTime":0,
                                  "endTime":3,
                                  "duration":10,
                                  "mute":false,
                                  "volume":0,
                                  "rate":1,
                                  "rotate":{"enable":false,
                                            "rotate":0},
                                  "filter":{"isLocalSource":true,
                                            "enable":false,
                                            "name":"",
                                            "strength":0,
                                            "type":"filter",
                                            "enabled":false},
                                  "effect":{"enable":false,
                                            "vignette":"",
                                            "sharpen":""},
                                  "transition":{"isLocalSource":false,"name":"",
                                                "duration":"",
                                                "timebase":60,
                                                "type":"transition"}}]}

        conf_a = json.dumps(config)
        params["config"] = conf_a
        conf_b = json.dumps(z_film_config)
        params["z_film_config"] = conf_b
        print(type(conf_a))
        print(conf_b)




if __name__ == '__main__':
    a = mod_data()
    a.getData()

