---
Official_getDbconfig:
  dec: '官网变量查询 '
  parameters:
    -
      url: /v1/get_dbconfig
      data:
        -
          code*: 13418483933@139.com
      header: {
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0)\
                Gecko/20100101 Firefox/71.0"
              }